### PR TITLE
[Feature] Parcel publications endpoint

### PR DESCRIPTION
**Pull request by NicoSantangelo**
Blocked by #70 (continuation)

@cazala What do you think of this: https://github.com/decentraland/marketplace/commit/514d8cb9cea87d4ac340282b102ede5863c8e3e7
I removed both the parcel data endpoint _and_ the hover event in an attempt to make things simpler, but that means no more "realtime" data on the server. You'll need to refresh to get the latest data.

### CODE REVIEW

**Comment by cazala** [comment]
> I removed both the parcel data endpoint and the hover event in an attempt to make things simpler, but that means no more "realtime" data on the server. You'll need to refresh to get the latest data.

I think that's fine 👍. Dragging the map would refresh the parcel data for the whole window anyway, right?

**Comment by NicoSantangelo** [comment]
> Dragging the map would refresh the parcel data for the whole window anyway, right?

Yes!
Rebased.

**Comment by cazala** [comment]
@NicoSantangelo the endpont `/api/parcels/:x/:y/publications` is working fine for me, but the `/api/parcels?nw&se` is always returning `publication: null` even for parcels that return publications by hitting the other endpoint, like this:

publications-endpoint

**Comment by NicoSantangelo** [comment]
Didn't see the comment! let me check

**Comment by NicoSantangelo** [comment]
@cazala Hmm it looks like it's working on my end

image

are you sure you have a `confirmed` and `open` publication for your parcel?

**Pull request merged**
