### PR TITLE
feat: adds tooltip to MANA components

### LINKED ISSUE #699: MANA Tooltip
## 🎉 Description

Add a tooltip to the mana component as shown in the wireframe:

Screen Shot 2022-06-15 at 13 53 57

* [ ] 🐛 This is a bug report.
* [x] 📈 This is a feature request.

## 📝 Details

To complete this task we should:

- [x] Add an optional `showTooltip` boolean prop to the `<Mana/>` component in [decentraland-ui](https://github.com/decentraland/ui) 
- [ ] Turn on the property in all the relevant places in the marketplace (item/nft cards, item/nft details, buy/sell/bid modals when it's not within an input)

### PR DESCRIPTION
**Pull request by Chakravarthy7102**
closes #699

### CODE REVIEW

**Comment by Chakravarthy7102** [comment]
> Sorry for the delay, one last thing. Would you mind fixing the conflicts in the `webapp/package.json` and `webapp/package-lock.json`?

done!

**Review by kevinszuchet — APPROVED** [review]
Great, thanks!

**Comment by kevinszuchet** [comment]
Hi @Chakravarthy7102, 

Just passing by to tell you that your changes are live 🥳 
image

Congrats, and thanks a lot for your help!

**Comment by Chakravarthy7102** [comment]
> Hi @Chakravarthy7102,
> 
> Just passing by to tell you that your changes are live partying_face image
> 
> Congrats, and thanks a lot for your help!



> Hi @Chakravarthy7102,
> 
> Just passing by to tell you that your changes are live partying_face image
> 
> Congrats, and thanks a lot for your help!

Hurrayy!!

**Pull request merged**
